title: Hector Rangel's Portfolio # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  This is my website showcasing my work.
  <br><br>
  if you would like me to build you a website for you or for your company please contact me.
  <br><br>
  
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
